"""!
@file DM_Types.py
@brief Typing-only Protocol describing the state and cross-mixin methods that DMCore's
    domain mixins (DM_Combat.py, DM_Dialogue.py, DM_Inventory.py, DM_Movement.py,
    DM_Persistence.py, DM_Rules.py, DM_Social.py, DM_Status.py) rely on but don't themselves
    define -- each is actually set
    up by DMCore.__init__ (DM_Core.py) or implemented by exactly one other mixin. Every
    mixin inherits from DMCoreProtocol so type checkers (Pylance/pyright) can resolve
    dm_core.<attr> across the whole composed class without each mixin file re-declaring the
    same attribute independently, which is what triggers pyright's
    reportIncompatibleVariableOverride/reportIncompatibleMethodOverride -- two unrelated
    sibling mixins both declaring, say, `event_bus: EventBus` looks to pyright like one
    overriding the other with an incompatible type, even though the types match. A single
    shared declaration site fixes that structurally.

    This has zero runtime effect: Protocol subclasses impose no behavior, and none of these
    stub method bodies (`...`) ever actually run -- Python's MRO always finds the real
    implementation on whichever concrete mixin defines it first, before it would ever reach
    this shared base. See DM_Core.py's class docstring for how the mixins compose.
"""

from typing import Protocol

from Event_Bus import EventBus


class DMCoreProtocol(Protocol):
    event_bus: EventBus
    skills: dict
    entities: dict
    entity_templates: dict
    scenario: dict
    scenario_entities: list
    persistent_entities: list
    rules: dict
    round_number: int
    current_target: str | None
    scenario_key: str
    player_name: str
    rooms: dict
    current_room_key: str | None
    visited_rooms: dict

    # Cross-mixin methods -- each actually implemented by exactly one mixin (see that
    # mixin's own file for the real body); declared here once so every other mixin calling
    # across to it type-checks without re-declaring the signature itself.
    def loot_entity(self, from_name, to_name) -> dict: ...
    def get_equip_slots(self, entity_name) -> list: ...
    def _publish_party_status(self) -> None: ...
    def apply_damage(self, entity_name, amount) -> int: ...
    def apply_healing(self, entity_name, amount) -> int: ...
    def apply_condition(self, entity_name, condition_name, duration=None, dismiss=None) -> None: ...
    def entity_matches_requirements(self, entity_name, requirements, opponent_name=None) -> bool: ...
    def describe_character(self, entity_name, toward_name=None) -> str: ...
    def describe_attitude(self, entity_name, toward_name) -> str: ...
    def get_attitude(self, entity_name, toward_name) -> list: ...
    def is_hostile(self, entity_name, toward_name) -> bool: ...
    def is_hidden(self, entity_name) -> bool: ...
    def is_locked(self, entity_name) -> bool: ...
    def is_closed(self, entity_name) -> bool: ...
    def is_identified(self, entity_name) -> bool: ...
    def resolve_action(self, entity_name, skill_name, difficulty=0, dice_penalty=0) -> dict: ...
    def dismiss_condition(self, entity_name, condition_name) -> bool: ...
    def roll_dice(self, dice, pips) -> int: ...
    def _choose_combat_target(self) -> str | None: ...
    def _get_target_name(self) -> str | None: ...
    def load_rules(self, rules_dir) -> None: ...
    def load_scenario_definition(self, scenario_name) -> None: ...
    def load_scenario(self, skip_llm_generation=False) -> None: ...
    def enter_room(self, room_key, arrival_band=1, skip_llm_generation=False) -> bool: ...
    def _instance_entities(self, entity_entries, party_pool=None, skip_llm_generation=False) -> list: ...
    def _current_room(self) -> dict | None: ...
    def _describe_scenario_characters(self) -> list: ...
    def get_current_hp(self, entity_name) -> int: ...
    def get_band(self, entity_name) -> int: ...
    def get_distance_between(self, entity_a, entity_b) -> int: ...
    def is_in_range(self, attacker_name, defender_name, ability) -> bool: ...
    def move_toward_or_away(self, entity_name, opponent_name, direction) -> dict | None: ...
    def _apply_party_formation(self) -> None: ...
    def get_challenge_rating(self, entity_name) -> int: ...
    def get_party_challenge_rating(self) -> int: ...
    def _apply_npc_generation(self, instance_name, party_pool, instance_names_so_far, skip_llm_generation) -> None: ...
