[[entity]]
name = "cleave"
supertype = "technique"
type = "martial"
subtype = "melee"
skill = [ "blades", "axes" ]
range = { minimum = 0, maximum = 1 }
targets = { number = 3, aoe = 0 }
damage_value = { dice = "user.weapon.dice", pips = "user.weapon.pips", bonus = "user.strength_damage" }
damage_tags = [ "slashing" ]