[[entity]]
name = "longsword"
supertype = "object"
subtype = "weapon"
skill = "blades"
max_hp = 10
ranges = { short = 0 }
damage_value = { dice = 1, pips = 2, bonus = "strength_damage" }
damage_tags = [ "slashing" ]
bulk = 1
value = 15
[entity.skills]
fortitude = { dice = 3, pips = 0 }

[[entity]]
name = "long bow"
supertype = "object"
subtype = "weapon"
skill = "missiles"
max_hp = 5
ranges = { short = 10, medium = 100, long = 250 }
damage_value = { dice = 2, pips = 2, bonus = 0 }
damage_tags = [ "piercing" ]
bulk = 1
value = 10
[entity.skills]
fortitude = { dice = 1, pips = 0 }

[[entity]]
name = "chain mail"
supertype = "object"
subtype = "armor"
max_hp = 20
armor_value = { dice = 2, pips = 0 }
armor_tags = [ "physical", "piercing", "bludgeoning", "slashing" ]
bulk = 1
value = 15
[entity.skills]
fortitude = { dice = 5, pips = 0 }

[[entity]]
name = "health potion"
supertype = "object"
subtype = "potion"
tags = [ "healing" ]
bulk = 0
value = 15
[entity.skills]
healing = { dice = 5, pips = 0 }
fortitude = { dice = 1, pips = 0 }