[range_modifiers]
[[range_modifiers.distance]] # point blank
minimum = 0
maximum = 3
modifier = { dice = 0, pips = 0, bonus = -5 }
[[range_modifiers.distance]] # short
minimum = 3
maximum = "short"
modifier = { dice = 0, pips = 0, bonus = 0 }
[[range_modifiers.distance]] # medium
minimum = "short"
maximum = "medium"
modifier = { dice = 0, pips = 0, bonus = 5 }
[[range_modifiers.distance]] # long
minimum = "medium"
maximum = "long"
modifier = { dice = 0, pips = 0, bonus = 10 }

[wounds]
[[wounds.effect]] # bruised
hp_per_remain = { minimum = 0.81, maximum = 0.99 }
description = "Absorbed most or all of the attack"

[[wounds.effect]] # stunned
hp_per_remain = { minimum = 0.60, maximum = 0.80 }
apply = { condition = "stunned", duration = "fleeting", dismiss = "none" }
description = "Moderate bruise or minor sprain; laceration; muscle tear; minor dislocation of joint."

[[wounds.effect]] # wounded
hp_per_remain = { minimum = 0.40, maximum = 0.59 }
apply = { condition = "wounded", duration = "permanent", dismiss = "healing" }
description = "Severe abrasion or sprain; deep laceration; torn ligaments; major dislocation or minor break."

[[wounds.effect]] # severe
hp_per_remain = { minimum = 0.20, maximum = 0.39 }
apply = { condition = "severe", duration = "permanent", dismiss = "healing" }
description = "Broken bone; gaping wound; ripped cartilage and muscle; concussion."

[[wounds.effect]] # incapacitated
hp_per_remain = { minimum = 0.10, maximum = 0.19 }
apply = { condition = "incapacitated", duration = "permanent", dismiss = "healing" }
test = { difficulty = 15, skill = ["fortitude", "willpower"], pass = "", fail = { condition = "unconscious", duration = "scene", dismiss = "healing" } }
description = "Multiple fracture; laceration in vital area; heavy concussion."

[[wounds.effect]] # mortal
hp_per_remain = { minimum = 0.01, maximum = 0.09 }
apply = { condition = "unconscious", duration = "permanent", dismiss = "healing", duration_minutes = 6 }
test = { skill = ["fortitude"], pass = "", fail = { condition = "dead", duration = "permanent", dismiss = "healing" } }
description = "Multiple internal injuries."

[[wounds.effect]] # dead
hp_per_remain = { minimum = 0, maximum = 0 }
apply = { condition = "dead", duration = "permanent", dismiss = "resurrection" }
description = "Broken neck; punctured lung; eviscerated."

[conditions]
[[conditions.condition]]
name = "stunned"
modifier = { dice = -1, pips = 0, bonus = 0 }

[[conditions.condition]]
name = "wounded"
modifier = { dice = -1, pips = 0, bonus = 0 }

[[conditions.condition]]
name = "severe"
modifier = { dice = -2, pips = 0, bonus = 0 }

[[conditions.condition]]
name = "incapacitated"
modifier = { dice = -3, pips = 0, bonus = 0 }

[[conditions.condition]]
name = "mortal"
modifier = { dice = -3, pips = 0, bonus = 0 }

[[conditions.condition]]
name = "dead"
modifier = { dice = 0, pips = 0, bonus = 0 }

[strength_damage]
skill = "strength"
divisor = 2