[[entity]]
name = "cleave"
supertype = "technique"
subtype = "martial"
description = "A wide, sweeping strike that can cut through multiple enemies at once."
skill = [ "blades", "axes" ]
difficulty = 10
range = { minimum = 0, maximum = 1 }
targets = { number = 3, aoe = 0 }
damage_value = { dice = "user.weapon.dice", pips = "user.weapon.pips", bonus = "user.strength_damage" }
damage_tags = [ "slashing" ]