"""!
@file DM_Types.py
@brief Typing-only Protocol describing the state and cross-mixin methods that DMCore's
    domain mixins (Combat_Actions.py, DM_Dialogue.py, DM_Inventory.py, DM_Movement.py,
    DM_Persistence.py, DM_Rules.py, DM_Social.py, DM_Status.py) rely on but don't themselves
    define -- each is actually set
    up by DMCore.__init__ (DM_Core.py) or implemented by exactly one other mixin. Every
    mixin inherits from DMCoreProtocol so type checkers (Pylance/pyright) can resolve
    dm_core.<attr> across the whole composed class without each mixin file re-declaring the
    same attribute independently, which is what triggers pyright's
    reportIncompatibleVariableOverride/reportIncompatibleMethodOverride -- two unrelated
    sibling mixins both declaring, say, `event_bus: EventBus` looks to pyright like one
    overriding the other with an incompatible type, even though the types match. A single
    shared declaration site fixes that structurally.

    This has zero runtime effect: Protocol subclasses impose no behavior, and none of these
    stub method bodies (`...`) ever actually run -- Python's MRO always finds the real
    implementation on whichever concrete mixin defines it first, before it would ever reach
    this shared base. See DM_Core.py's class docstring for how the mixins compose.
"""

from typing import Any, Protocol

from Event_Bus import EventBus


class DMCoreProtocol(Protocol):
    event_bus: EventBus
    world: object
    skills: dict
    entities: dict
    universal_abilities: set
    entity_templates: dict
    scenario: dict
    scenario_entities: list
    persistent_entities: list
    rules: dict
    slot_store: object
    save_parts: list
    law_enforcement: object
    round_number: int
    current_block: int
    watch_rotation_index: int
    pending_downtime: dict | None
    current_target: str | None
    conversation_partner: dict | None
    scenario_key: str
    player_name: str
    rooms: dict
    current_room_key: str | None
    visited_rooms: dict
    removed_entities: set
    locations: dict
    current_location_key: str | None
    legal_records: dict
    pending_reports: list
    pending_arrest: dict | None
    known_locations: set
    _last_scene_roster: tuple | None
    _pending_population: list
    _population_in_flight: int
    _population_done: Any

    # Cross-mixin methods -- each actually implemented by exactly one mixin (see that
    # mixin's own file for the real body); declared here once so every other mixin calling
    # across to it type-checks without re-declaring the signature itself.
    def loot_entity(self, from_name, to_name) -> dict: ...
    def place_new_item(self, destination_name, item_name) -> bool: ...
    def transfer_item(self, from_name, to_name, item_name) -> bool: ...
    def transfer_currency(self, from_name, to_name, amount=None) -> int: ...
    def nudge_attitude_from_event(self, entity_name, toward_name, event_name, magnitude) -> None: ...
    def get_equip_slots(self, entity_name) -> list: ...
    def _sync_mount_bands(self, mover_name) -> None: ...
    def _publish_party_status(self) -> None: ...
    def apply_downtime_upkeep(self, blocks) -> None: ...
    def describe_character(self, entity_name, toward_name=None) -> str: ...
    def describe_attitude(self, entity_name, toward_name) -> str: ...
    def get_attitude(self, entity_name, toward_name) -> list: ...
    def is_hostile(self, entity_name, toward_name) -> bool: ...
    def _arm_if_turned_hostile(self, entity_name, toward_name) -> None: ...
    def is_hidden(self, entity_name) -> bool: ...
    def is_locked(self, entity_name) -> bool: ...
    def is_closed(self, entity_name) -> bool: ...
    def _choose_combat_target(self) -> str | None: ...
    def _target_is_engaged(self) -> bool: ...
    def _any_hostile_present(self) -> bool: ...
    def _resume_pending_downtime(self) -> None: ...
    def _advance_pending_travel(self) -> dict: ...
    def _advance_pending_rest(self) -> dict: ...
    def _unique_entity_key(self, base_name) -> str: ...
    def _get_target_name(self, include_background=False, include_objects=True) -> str | None: ...
    def _is_party_member(self, entity_name) -> bool: ...
    def _is_background(self, entity_name) -> bool: ...
    def load_rules(self, rules_dir) -> None: ...
    def _resolve_player_name(self, template=None) -> str: ...
    def _rename_player_entity(self, new_name) -> bool: ...
    def load_scenario_definition(self, scenario_name) -> None: ...
    def load_scenario(self, skip_llm_generation=False) -> None: ...
    def enter_room(self, room_key, arrival_band=1, skip_llm_generation=False) -> bool: ...
    def _instance_entities(self, entity_entries, party_pool=None, skip_llm_generation=False) -> list: ...
    def _current_room(self) -> dict | None: ...
    def _current_scene_name(self) -> str: ...
    def _current_scene_description(self) -> str: ...
    def _describe_scenario_characters(self) -> list: ...
    def _publish_scene_roster(self) -> None: ...
    def _set_conversation_partner(self, target_name) -> None: ...
    def _publish_conversation_partner(self) -> None: ...
    def _tick_conversation_partner(self) -> None: ...
    def _population_prompt_settings(self) -> dict: ...
    def _population_settings(self) -> dict: ...
    def _current_polity_language(self) -> str | None: ...
    def _resolve_region_polity(self, x, y) -> str | None: ...
    def _find_polity(self, name) -> dict | None: ...
    def format_currency(self, amount) -> str: ...
    def current_polity(self) -> str | None: ...
    def report_crime(self, crime, offender, victim=None, subject=None) -> list: ...
    def note_assault(self, attacker, victim) -> None: ...
    def note_kill(self, killer, victim) -> None: ...
    def observe_ability_use(self, caster, ability) -> None: ...
    def check_presence(self) -> None: ...
    def legal_facts_for(self, entity_name) -> list: ...
    def _is_enforcer(self, name) -> bool: ...
    def _sees_through(self, witness, subject) -> bool: ...
    def _law_settings(self) -> dict: ...
    def _display_name(self, name) -> str | None: ...
    def _identity_label(self, identity) -> str: ...
    def advance_blocks(self, blocks=1) -> dict: ...
    def get_time_state(self) -> dict: ...
    def _enter_location(self, location_key, arrival_room=None, arrival_band=1, skip_llm_generation=False) -> None: ...
    def move_toward_or_away(self, entity_name, opponent_name, direction) -> dict | None: ...
    def _apply_party_formation(self) -> None: ...
    def _apply_pending_population(self) -> None: ...
    def _apply_npc_generation(self, instance_name, party_pool, instance_names_so_far, skip_llm_generation) -> None: ...
    def _all_known_instance_names(self) -> list: ...
    def _current_ground_items(self) -> list: ...
    def _on_item_interaction_detected(self, data) -> None: ...
    def remove_entity_from_scene(self, name) -> dict: ...
    def _attempt_entity_removal(self, input_text) -> dict: ...
    def _attempt_dialogue_promotion(self, address_phrase) -> str | None: ...
    def _literal_dialogue_target(self, input_text) -> str | None: ...
